print('What is your name?')
name = input()
print('How old are you?')
age = input()
print('Where do you live?')
place = input()
print('\nThis is '+name)
print('It is '+age)
print('(S)he lives in '+place)